### ISSUE TITLE
A property exist but cannot be read

### ISSUE THREAD

**Issue by marccollin** [A1rPun/transForm#1]
I got problem when i call transform.deserialize in the success method of a ajax call

 transForm.deserialize("#contactInformationForm",data);

 My json data

```
{  
   "lodgerId":1,
   "firstName":"boby",
   "lastName":"Smit",
   "birthdate":"1979-03-02",
   "lodgerStatusId":0,
   "entryDate":"2015-07-22",
   "releaseDate":null,
   "phone":{  
      "phoneId":2,
      "phone":"(438) 412-3221",
      "phoneType":null,
      "extension":0
   },
   "identityCardList":[  
      {  
         "identityCardId":1,
         "identityCardType":{  
            "identityCardTypeId":1,
            "identityCardType":"Birth act",
            "dateFormat":null
         },
         "identyCardValue":"sdfasd",
         "expiration":null,
         "lodgerOwn":false
      }
   ],
   "oldAddress":{  
      "addressId":1,
      "name":"Père",
      "address":"906 boulé",
      "phone":{  
         "phoneId":1,
         "phone":"4526777225",
         "phoneType":null,
         "extension":0
      }
   },
   "vehicle":{  
      "vehicleId":1,
      "modelId":0,
      "color":"#e1e1e1",
      "licencePlate":"h8x2n4",
      "year":2005
   },
   "inactive":false
}
```

```
<form id="contactInformationForm">
  <input type="hidden" class="form-control" name="lodgerId" id="lodgerId">
  <input type="text" class="form-control" id="lodgerFirstName" name="firstName">
  <input type="text" class="form-control" id="lodgerLastName" name="lastName">
  <input type="hidden" id="oldAddressAddressId" name="oldAddress.addressId">
  <input type="text" class="form-control" id="oldAddressName" name="oldAddress.name">
  <input type="text" class="form-control" id="oldAddressAddress" name="oldAddress.address" >
  <input type="hidden" name="identityCardList[0].identityCardId">
  <input type="text" class="form-control" id="idCardValue1" name="identityCardList[0].identyCardValue">
....
</form>
```

In the method getFieldValue, at the list  var part = ref[parts[i]]; i get
Cannot read property 'identityCardId' of undefined

**Comment by A1rPun** [comment]
Hey marccollin, thanks for submitting. I can't reproduce your issue. Created a [jsfiddle](https://jsfiddle.net/x1o9dp75/) for a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/). I'm looking for a way to get the same issue now.

**Comment by marccollin** [comment]
i created an example here: https://jsfiddle.net/0286yehb/4/

only need to click on the button at the to right, if you check the console, you will see the error.

**Comment by A1rPun** [comment]
Thanks for creating a SSCCE, this helped me debug this error very fast. It throws an error because `<input name="identityCardList[1].identityCardId">` doesn't have a corresponding object in the `identityCardList` array. What did you expect? Maybe I can meet your expectations here.

EDIT
I've created a fix which just clears the input when there is no corresponding object in the array. Will be pushed anytime soon
