### ISSUE TITLE
label and input

### ISSUE THREAD

**Issue by marccollin** [A1rPun/transForm#9]
hi

is it possible to add a functionnality to push value automatically to the label when we have a hidden field

```
<label for="input.required2"></label><br />
<input type="hidden" name="input.required2" value="input hidden to label"/>
```

after consideration, data-transform-text could be a great alternative

**Comment by A1rPun** [comment]
Hey,
Hopefully the `data-transform-text` solution is sufficient for you. How does you solution look like?
In an earlier stage of `transForm` I had two-way databinding working because angular did it too (it was cool back then), I removed it because it was buggy.
